@id = 4
@slug = album-{{id}}


### Create a new Album
POST {{$dotenv URL}}:{{$dotenv PORT}}/albums
Content-Type: application/json

{
    "title": "Album {{id}}",
    "slug": "{{slug}}",
    "description": "This is the first album"
}


### Get Album by ID
GET {{$dotenv URL}}:{{$dotenv PORT}}/albums/{{id}}


### Update album by ID
PATCH {{$dotenv URL}}:{{$dotenv PORT}}/albums/{{id}}
Content-Type: application/json

{
    "title": "Changed",
    "description": "changed aswell"
}

### Add an title image to an album
PATCH {{$dotenv URL}}:{{$dotenv PORT}}/albums/{{id}}
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="title_image"; filename="img_02.jpg"
Content-Type: image/jpeg

< ./test_data/img_02.jpg
--MfnBoundry--


### Delete Album by ID
DELETE {{$dotenv URL}}:{{$dotenv PORT}}/albums/{{id}}


### Add one image to an album
POST {{$dotenv URL}}:{{$dotenv PORT}}/albums/{{id}}
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="files"; filename="img_01.jpg"
Content-Type: image/jpeg

< ./test_data/img_01.jpg
--MfnBoundry--


### Delete an image from an album
DELETE {{$dotenv URL}}:{{$dotenv PORT}}/albums/{{id}}/images/8


### Add multiple images to an album
POST {{$dotenv URL}}:{{$dotenv PORT}}/albums/{{id}}
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="files"; filename="img_01.jpg"
Content-Type: image/jpeg

< ./test_data/img_01.jpg
--MfnBoundry
Content-Disposition: form-data; name="files"; filename="img_02.jpg"
Content-Type: image/jpeg

< ./test_data/img_02.jpg
--MfnBoundry
Content-Disposition: form-data; name="files"; filename="img_03.jpg"
Content-Type: image/jpeg

< ./test_data/img_03.jpg
--MfnBoundry--


