### Get a User by ID
GET {{$dotenv URL}}:{{$dotenv PORT}}/users/1


### Create a new User
POST {{$dotenv URL}}:{{$dotenv PORT}}/users/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "test@test.de",
    "password": "123456"
}

### Get logged in User
GET {{$dotenv URL}}:{{$dotenv PORT}}/users/whoami
